apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-t0mo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-tstq-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-t0mo@sha256:64fdd767ded893b7195b033e9cd504f5063afa0d8a98b669aa6f0b4b37318847
        name: my-python
        resources: {}
status: {}
